name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo secrets
        run: |
          echo "Host ${{ secrets.EC2_INSTANCE_IP }}" | sed 's/./& /g'
          echo "Username ${{ secrets.SSH_USERNAME }}" | sed 's/./& /g'
          echo "Key ${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/./& /g'
          echo "Passphrase ${{ secrets.SERVER_PASSPHRASE }}" | sed 's/./& /g'

      - name: Build Docker image
        run: docker build -t myapp .
        
      - name: Save Docker image
        run: docker save myapp:latest > myapp.tar
        
      - name: Transfer Docker image
        uses: appleboy/scp-action@v0.1.4
        with:
          host:  ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "myapp.tar"
          target: "/usr/bin/myapp"

      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker load -i ~/myapp.tar
            docker run -d --name myapp -p 80:80 myapp:latest
