name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build -t organization-service .
        
      - name: Save Docker image
        run: docker save organization-service:latest > organization-service.tar
        
      - name: Transfer Docker image
        uses: appleboy/scp-action@v0.1.4
        with:
          host:  65.2.9.18
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "organization-service.tar"
          target: "/usr/bin/organization-service"

      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /usr/bin/organization-service
            sudo docker load -i organization-service.tar
            sudo docker run --name organization-service -dp 3006:3006 --env-file .env organization-service
